# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: GetStocks

on:
  schedule:
    - cron: '0 14 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-stocks:
    name: Get Mean Reversion Stocks
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        
      - uses: actions/checkout@v2

      - name: Delete Old csv files
        run: echo `date` && rm -f data/mean_reversion.csv
        
      - name: Install python packages
        run: python -m pip install -r requirements.txt
        
      - name: Get Stocks
        run: python 01_mean_reversion_BO_at_8_50.py

      - uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
        name: Commit and Push
