# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: GetStocks

on:
  schedule:
    - cron: '0 14 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-stocks:
    name: Get Mean Reversion Stocks
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Delete Old csv files
        run: echo `date` && rm -force data/mean_reversion.csv
        
      - name: Get Stocks
        run: python 01_mean_reversion_BO_at_8_50.py

      - uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
        name: Commit and Push
