# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: GetStocks

on:
  schedule:
    - cron: '*/5 * * * 1-5'

jobs:
  get-stocks:
    name: Get Mean Reversion Stocks
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        
      - name: Get Stocks
        run: python 01_mean_reversion_BO_at_8_50.py

      - uses: actions-js/push@1.3
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
        name: Commit and Push
